services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres-db-drawerlink
    restart: unless-stopped
    environment:
      POSTGRES_USER: drawerlinkuser
      POSTGRES_PASSWORD: drawerlinkuser
      POSTGRES_DB: drawer_link
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
